export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="mk">
      <head><meta name="robots" content="noindex,nofollow" /></head>
      <body>{children}</body>
    </html>
  )
}
